import type { Metadata } from "next";

import { Toaster } from "react-hot-toast";

import "@/app/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Toaster />
            {children}
        </>
    );
}
